-- Paste into Prisma Studio → SQL → Run SQL
-- If rows already exist, run the three DELETEs first, then the two INSERTs.

-- DELETE FROM "ConversationLog";
-- DELETE FROM "Answer";
-- DELETE FROM "Question";

INSERT INTO "Question" (id, category, prompt, aliases, active, "createdAt", "updatedAt")
VALUES
  ('faq_001', 'greeting', 'Hello', ARRAY['hi', 'hey', 'good morning', 'good afternoon', 'who are you']::TEXT[], true, NOW(), NOW()),
  ('faq_002', 'services', 'What services do you provide?', ARRAY['what do you do', 'what can you build', 'software engineering services', 'web development services', 'full stack services']::TEXT[], true, NOW(), NOW()),
  ('faq_003', 'services', 'Do you do full-stack applications?', ARRAY['full stack developer', 'frontend and backend', 'end to end development']::TEXT[], true, NOW(), NOW()),
  ('faq_004', 'services', 'Do you build APIs?', ARRAY['api development', 'rest api', 'backend apis', 'laravel api']::TEXT[], true, NOW(), NOW()),
  ('faq_005', 'services', 'Do you design databases?', ARRAY['database design', 'postgres schema', 'mysql database', 'mongodb schema']::TEXT[], true, NOW(), NOW()),
  ('faq_006', 'services', 'Can you rebuild or improve an existing website?', ARRAY['redesign my site', 'migrate my website', 'improve performance', 'seo work']::TEXT[], true, NOW(), NOW()),
  ('faq_007', 'stack', 'What technologies do you specialize in?', ARRAY['tech stack', 'what languages do you use', 'skills', 'tools you use']::TEXT[], true, NOW(), NOW()),
  ('faq_008', 'stack', 'What is your experience with Next.js?', ARRAY['nextjs experience', 'do you know next.js', 'next js developer']::TEXT[], true, NOW(), NOW()),
  ('faq_009', 'stack', 'What is your experience with React?', ARRAY['react.js', 'reactjs experience', 'do you know react']::TEXT[], true, NOW(), NOW()),
  ('faq_010', 'stack', 'What is your experience with Laravel?', ARRAY['laravel developer', 'php laravel', 'do you know laravel']::TEXT[], true, NOW(), NOW()),
  ('faq_011', 'stack', 'What is your experience with Node.js?', ARRAY['nodejs', 'express.js', 'node backend']::TEXT[], true, NOW(), NOW()),
  ('faq_012', 'stack', 'Do you work with PostgreSQL and MySQL?', ARRAY['postgres', 'mysql', 'sql databases', 'mongodb experience']::TEXT[], true, NOW(), NOW()),
  ('faq_013', 'stack', 'Do you use AWS or Docker?', ARRAY['aws experience', 'docker deploys', 'hosting', 'deployment']::TEXT[], true, NOW(), NOW()),
  ('faq_014', 'stack', 'Do you work with TypeScript?', ARRAY['typescript experience', 'javascript es6']::TEXT[], true, NOW(), NOW()),
  ('faq_015', 'projects', 'Can you show examples of similar projects?', ARRAY['portfolio projects', 'case studies', 'what have you built', 'examples of your work', 'live websites']::TEXT[], true, NOW(), NOW()),
  ('faq_016', 'projects', 'Have you built booking or marketplace products?', ARRAY['hotel booking', 'directory website', 'marketplace', 'e-commerce']::TEXT[], true, NOW(), NOW()),
  ('faq_017', 'projects', 'Have you built payment or subscription products?', ARRAY['stripe', 'payment gateway', 'subscriptions', 'saas']::TEXT[], true, NOW(), NOW()),
  ('faq_018', 'projects', 'What kind of project types do you take?', ARRAY['what projects do you accept', 'ideal client', 'what do you not do']::TEXT[], true, NOW(), NOW()),
  ('faq_019', 'process', 'What is your development process?', ARRAY['how do you work', 'workflow', 'project process', 'how do you start a project']::TEXT[], true, NOW(), NOW()),
  ('faq_020', 'process', 'What is your approach to testing and code quality?', ARRAY['testing', 'qa', 'code quality', 'do you write tests']::TEXT[], true, NOW(), NOW()),
  ('faq_021', 'process', 'How do you handle project updates and progress reporting?', ARRAY['status updates', 'communication during project', 'progress reports', 'weekly updates']::TEXT[], true, NOW(), NOW()),
  ('faq_022', 'process', 'How do you handle NDA or confidential work?', ARRAY['nda', 'confidential', 'can you work under nda', 'private projects']::TEXT[], true, NOW(), NOW()),
  ('faq_023', 'collaboration', 'Do you work with existing teams or only solo?', ARRAY['join my team', 'work with designers', 'collaborate with developers', 'agency partner']::TEXT[], true, NOW(), NOW()),
  ('faq_024', 'collaboration', 'Can you work with our existing codebase?', ARRAY['legacy laravel', 'existing react app', 'take over a project']::TEXT[], true, NOW(), NOW()),
  ('faq_025', 'pricing', 'What is your rate?', ARRAY['how much do you charge', 'pricing', 'hourly rate', 'what is your rate for a website', 'cost of a project']::TEXT[], true, NOW(), NOW()),
  ('faq_026', 'pricing', 'What is your rate for a landing page or small site?', ARRAY['cheap website', 'small project cost', 'brochure site']::TEXT[], true, NOW(), NOW()),
  ('faq_027', 'pricing', 'Do you take fixed-price or retainer work?', ARRAY['fixed bid', 'monthly retainer', 'engagement models', 'ongoing contract']::TEXT[], true, NOW(), NOW()),
  ('faq_028', 'timeline', 'How long does a project take?', ARRAY['timeline', 'how soon can you start', 'duration', 'delivery time']::TEXT[], true, NOW(), NOW()),
  ('faq_029', 'timeline', 'How soon can you start?', ARRAY['availability this week', 'start immediately', 'when are you free']::TEXT[], true, NOW(), NOW()),
  ('faq_030', 'timeline', 'What is the timeline for a large web application?', ARRAY['big project duration', 'saas timeline', 'complex build']::TEXT[], true, NOW(), NOW()),
  ('faq_031', 'availability', 'Are you available for freelance work?', ARRAY['hire you', 'are you free', 'open for work', 'new opportunities']::TEXT[], true, NOW(), NOW()),
  ('faq_032', 'availability', 'Where are you based and what timezone do you work in?', ARRAY['location', 'timezone', 'maldives', 'uae', 'remote']::TEXT[], true, NOW(), NOW()),
  ('faq_033', 'communication', 'How do you prefer to communicate?', ARRAY['whatsapp', 'email', 'slack', 'working style']::TEXT[], true, NOW(), NOW()),
  ('faq_034', 'communication', 'How can I contact you?', ARRAY['email address', 'phone number', 'whatsapp number', 'contact details']::TEXT[], true, NOW(), NOW()),
  ('faq_035', 'maintenance', 'How do you handle maintenance and support after delivery?', ARRAY['after launch', 'bug fixes after delivery', 'support plan', 'warranty']::TEXT[], true, NOW(), NOW()),
  ('faq_036', 'maintenance', 'Do you offer hosting and monitoring?', ARRAY['will you host it', 'uptime', 'server management']::TEXT[], true, NOW(), NOW()),
  ('faq_037', 'experience', 'How many years of experience do you have?', ARRAY['years of experience', 'how long have you been a developer', 'seniority']::TEXT[], true, NOW(), NOW()),
  ('faq_038', 'experience', 'Where have you worked?', ARRAY['employers', 'centurion', 'fujtown', 'ferisoft', 'aursoft', 'work history']::TEXT[], true, NOW(), NOW()),
  ('faq_039', 'contact', 'Can we schedule a call?', ARRAY['book a meeting', 'discovery call', 'let''s talk', 'follow up']::TEXT[], true, NOW(), NOW()),
  ('faq_040', 'stack', 'Do you work with Vue.js?', ARRAY['vue', 'vuejs', 'do you know vue']::TEXT[], true, NOW(), NOW()),
  ('faq_041', 'stack', 'Do you use Tailwind CSS?', ARRAY['tailwind', 'bootstrap', 'css frameworks']::TEXT[], true, NOW(), NOW()),
  ('faq_042', 'stack', 'What is your experience with PHP?', ARRAY['php developer', 'plain php', 'codeigniter']::TEXT[], true, NOW(), NOW()),
  ('faq_043', 'stack', 'Do you work with Firebase?', ARRAY['firebase', 'google firebase', 'realtime database']::TEXT[], true, NOW(), NOW()),
  ('faq_044', 'stack', 'Can you build authentication and role-based access?', ARRAY['login system', 'user roles', 'admin permissions', 'rbac']::TEXT[], true, NOW(), NOW()),
  ('faq_045', 'stack', 'Do you build admin dashboards?', ARRAY['admin panel', 'cms', 'back office', 'operations dashboard']::TEXT[], true, NOW(), NOW()),
  ('faq_046', 'services', 'Can you help with SEO and page speed?', ARRAY['core web vitals', 'slow website', 'google ranking', 'lighthouse']::TEXT[], true, NOW(), NOW()),
  ('faq_047', 'services', 'Do you make websites mobile responsive?', ARRAY['mobile friendly', 'responsive design', 'works on phone']::TEXT[], true, NOW(), NOW()),
  ('faq_048', 'services', 'Can you build a bilingual English and Arabic site?', ARRAY['arabic website', 'rtl', 'multilingual', 'two languages']::TEXT[], true, NOW(), NOW()),
  ('faq_049', 'projects', 'Tell me about the FOIZ project.', ARRAY['foiz', 'fujairah oil', 'oil marketplace']::TEXT[], true, NOW(), NOW()),
  ('faq_050', 'projects', 'Tell me about SisTouristVilla.', ARRAY['hotel website', 'sistouristvilla', 'villa booking']::TEXT[], true, NOW(), NOW()),
  ('faq_051', 'projects', 'Tell me about fujtown.com.', ARRAY['fujtown directory', 'business listing site']::TEXT[], true, NOW(), NOW()),
  ('faq_052', 'projects', 'Have you built an inventory or POS system?', ARRAY['inventory software', 'point of sale', 'stock management']::TEXT[], true, NOW(), NOW()),
  ('faq_053', 'projects', 'Have you built a learning or coaching platform?', ARRAY['online courses', 'fitness app', 'ypt', 'lms']::TEXT[], true, NOW(), NOW()),
  ('faq_054', 'process', 'Who owns the code and the accounts when we finish?', ARRAY['intellectual property', 'source code ownership', 'github access', 'who owns the repo']::TEXT[], true, NOW(), NOW()),
  ('faq_055', 'process', 'Do you provide documentation and handover?', ARRAY['docs', 'readme', 'how do we take over', 'knowledge transfer']::TEXT[], true, NOW(), NOW()),
  ('faq_056', 'process', 'How do you handle change requests after we agree scope?', ARRAY['scope creep', 'extra features', 'revisions', 'change order']::TEXT[], true, NOW(), NOW()),
  ('faq_057', 'process', 'Do you work from Figma or do you also design?', ARRAY['ui design', 'figma', 'do you need a designer', 'ux']::TEXT[], true, NOW(), NOW()),
  ('faq_058', 'process', 'What do you need from me to start?', ARRAY['requirements', 'brief', 'kickoff', 'what access do you need']::TEXT[], true, NOW(), NOW()),
  ('faq_059', 'process', 'Do you use Git and code review?', ARRAY['github', 'version control', 'pull requests', 'ci cd']::TEXT[], true, NOW(), NOW()),
  ('faq_060', 'process', 'How do you handle security on a web app?', ARRAY['security', 'https', 'sql injection', 'xss', 'hardening']::TEXT[], true, NOW(), NOW()),
  ('faq_061', 'collaboration', 'Can you subcontract for an agency?', ARRAY['white label', 'agency developer', 'overflow work']::TEXT[], true, NOW(), NOW()),
  ('faq_062', 'collaboration', 'Do you speak English well enough for client work?', ARRAY['english', 'language', 'communication skills']::TEXT[], true, NOW(), NOW()),
  ('faq_063', 'pricing', 'How do payments work?', ARRAY['invoice', 'deposit', 'payment terms', 'milestone payments']::TEXT[], true, NOW(), NOW()),
  ('faq_064', 'pricing', 'Do you build WordPress sites?', ARRAY['wordpress', 'elementor', 'woocommerce']::TEXT[], true, NOW(), NOW()),
  ('faq_065', 'pricing', 'Do you build native iOS or Android apps?', ARRAY['mobile app', 'react native', 'flutter', 'app store']::TEXT[], true, NOW(), NOW()),
  ('faq_066', 'availability', 'Do you work weekends or evenings?', ARRAY['after hours', 'timezone overlap', 'weekend work']::TEXT[], true, NOW(), NOW()),
  ('faq_067', 'availability', 'Are you hiring or looking for a full-time job?', ARRAY['job offer', 'join our company', 'full time role', 'relocation']::TEXT[], true, NOW(), NOW()),
  ('faq_068', 'experience', 'What did you do at Centurion PLC?', ARRAY['centurion plc', 'current job', 'maldives job']::TEXT[], true, NOW(), NOW()),
  ('faq_069', 'experience', 'What did you do at Fujtown?', ARRAY['fujtown llc', 'uae experience']::TEXT[], true, NOW(), NOW()),
  ('faq_070', 'experience', 'What is your education?', ARRAY['degree', 'university', 'bscs', 'diploma']::TEXT[], true, NOW(), NOW()),
  ('faq_071', 'experience', 'Where can I see your GitHub or résumé?', ARRAY['github', 'cv', 'resume', 'linkedin']::TEXT[], true, NOW(), NOW()),
  ('faq_072', 'maintenance', 'What happens if something breaks after launch?', ARRAY['bugs after go live', 'hotfix', 'production issue']::TEXT[], true, NOW(), NOW()),
  ('faq_073', 'contact', 'Why should I hire you instead of an agency?', ARRAY['why you', 'vs agency', 'vs freelancer marketplace']::TEXT[], true, NOW(), NOW());

INSERT INTO "Answer" (id, "questionId", variant, body, "createdAt", "updatedAt")
VALUES
  ('ans_001_1', 'faq_001', 'default', 'I’m Raza’s site assistant. I can answer questions about services, stack, projects, timelines, and how to start work. Ask anything — if I don’t have it, I’ll take your email and phone so he can follow up.', NOW(), NOW()),
  ('ans_002_1', 'faq_002', 'default', 'I build production web products end to end: public sites, admin tools, APIs, and databases. Typical work is React or Next.js on the front, Laravel, Node, or PHP on the back, with PostgreSQL, MySQL, or MongoDB. Directories, booking, marketplaces, and coaching platforms are a natural fit.', NOW(), NOW()),
  ('ans_003_1', 'faq_003', 'default', 'Yes. I ship UI, APIs, and deploys as one piece of work. Recent roles at Fujtown and Centurion PLC are full-stack on live platforms, not front-end-only or ticket-only backend.', NOW(), NOW()),
  ('ans_004_1', 'faq_004', 'default', 'Yes. REST APIs in Laravel, Node/Express, and PHP — including third-party integrations. At Ferisoft that was a core part of the job; FOIZ used Laravel and PostgreSQL for API and query work.', NOW(), NOW()),
  ('ans_005_1', 'faq_005', 'default', 'Yes. I model PostgreSQL and MySQL for product data, and MongoDB when the document shape fits. Inventory, booking, directories, and payments all need a schema that stays fast after launch — that’s the bar.', NOW(), NOW()),
  ('ans_006_1', 'faq_006', 'default', 'Yes. I take existing Laravel, PHP, React, or Next.js products and tighten performance, SEO, and reliability. At Fujtown, server hardening cut downtime about 15%, and debugging dropped production bugs about 30%. Send the URL and what hurts.', NOW(), NOW()),
  ('ans_007_1', 'faq_007', 'default', 'Day to day: Next.js, React, TypeScript, JavaScript, Tailwind, Laravel, PHP, Node.js, Vue.js, MongoDB, PostgreSQL, MySQL, Firebase, AWS, and Docker. PHP since 2015; React and Laravel are the pair I reach for most.', NOW(), NOW()),
  ('ans_008_1', 'faq_008', 'default', 'I have used Next.js in production since 2023 — product work at Fujtown and this portfolio. YPT’s coaching platform is Next.js with a Laravel API. I am comfortable with App Router, server routes, and keeping the front fast.', NOW(), NOW()),
  ('ans_009_1', 'faq_009', 'default', 'React since 2019, through Aursoft, Fujtown, and Centurion. Interfaces, design collaboration, and production UIs — not demos. I also work in Vue when the product is already there, as on fujtown.com.', NOW(), NOW()),
  ('ans_010_1', 'faq_010', 'default', 'Laravel since 2018. It has been the backbone of directories, booking, driving-school ops, APIs, and admin tools. I also know CodeIgniter when a legacy PHP app needs care.', NOW(), NOW()),
  ('ans_011_1', 'faq_011', 'default', 'Node.js and Express since 2021 at Ferisoft — APIs, Firebase, and integrations. I still use Node beside Laravel when a product needs both, including this site’s routes.', NOW(), NOW()),
  ('ans_012_1', 'faq_012', 'default', 'Yes. PostgreSQL and MySQL across Aursoft, Ferisoft, and Fujtown. MongoDB when the product wants documents. FOIZ is Laravel + PostgreSQL; several live sites run MySQL.', NOW(), NOW()),
  ('ans_013_1', 'faq_013', 'default', 'Yes. At Aursoft I ran AWS EC2, S3, and RDS with 99.9% uptime and automated deploys. Docker is in the toolkit. I also ship on cPanel, Vercel, and typical PHP hosts when that is what the product already uses.', NOW(), NOW()),
  ('ans_014_1', 'faq_014', 'default', 'Yes. TypeScript and modern JavaScript on Next.js and React work. This portfolio is TypeScript. I don’t force TS onto a Laravel Blade app if it would slow the team down.', NOW(), NOW()),
  ('ans_015_1', 'faq_015', 'default', 'Live work includes FOIZ (oil marketplace APIs), SisTouristVilla (hotel booking and payments), fujtown.com (business directory), a fitness coaching platform with subscriptions, a Dutch driving-school system, and an inventory/POS. See /work. Some recent work is under NDA and can’t be named.', NOW(), NOW()),
  ('ans_016_1', 'faq_016', 'default', 'Yes. SisTouristVilla is booking + payments. fujtown.com is a directory with registration, search, and roles. FOIZ is marketplace-side API work. Those are the closest public examples.', NOW(), NOW()),
  ('ans_017_1', 'faq_017', 'default', 'Yes. SisTouristVilla includes a payment gateway. The coaching platform has authentication, payments, and subscriptions. I integrate the gateway you already use rather than inventing a new one.', NOW(), NOW()),
  ('ans_018_1', 'faq_018', 'default', 'Best fit: web products that have to stay live — Laravel/React/Next platforms, APIs, directories, booking, admin tools, and performance work. I don’t take mobile-native apps or chain/crypto work. If the brief is unclear, the contact form is the right next step.', NOW(), NOW()),
  ('ans_019_1', 'faq_019', 'default', 'Short brief first (goal, URL, timing, budget). Then a scoped plan: what ships, what waits, and how we’ll talk. I build in slices you can click, not a six-month reveal. Deploys stay boring — staging, then production.', NOW(), NOW()),
  ('ans_020_1', 'faq_020', 'default', 'I test the paths that break products: payments, booking, auth, and API contracts. Reviews and staging before production. At Fujtown, focused debugging cut production bugs about 30%. I don’t pad a quote with a theatre of unused test frameworks.', NOW(), NOW()),
  ('ans_021_1', 'faq_021', 'default', 'Async by default: email or WhatsApp with what shipped, what’s next, and blockers. For longer work, a short weekly note is enough. You will not need a stand-up to know whether the build is moving.', NOW(), NOW()),
  ('ans_022_1', 'faq_022', 'default', 'Yes. Part of my recent work is under NDA and is not listed on /work. I can talk about the problem, my role, and the stack without naming protected systems. Send an NDA if you need one before the brief.', NOW(), NOW()),
  ('ans_023_1', 'faq_023', 'default', 'Both. I have shipped inside product teams (Fujtown, Centurion) and as the engineer owning a build. I work fine next to designers, PMs, and other developers. I can also take a scoped product solo if that is what you need.', NOW(), NOW()),
  ('ans_024_1', 'faq_024', 'default', 'Yes. Most of the useful work is already-running PHP, Laravel, React, or Next.js. I read the repo, note risk, then change what matters. A handover and access list is enough to start.', NOW(), NOW()),
  ('ans_025_1', 'faq_025', 'default', 'I quote from a brief, not a fake hourly board. The contact form uses USD 100–5,000 for typical slices of product work. Larger platforms are scoped separately. If you know the outcome, I’ll price the work to get there.', NOW(), NOW()),
  ('ans_026_1', 'faq_026', 'default', 'Small public sites sit at the lower end of the USD 100–5,000 range on the contact form, depending on copy, CMS, and whether you need forms, SEO, or a CMS. Send the URL or a reference and a budget mark.', NOW(), NOW()),
  ('ans_027_1', 'faq_027', 'default', 'Both. A fixed quote for a defined slice, or a retainer for ongoing support and performance (the contact form has that topic). I don’t start open-ended builds without a cap you can see.', NOW(), NOW()),
  ('ans_028_1', 'faq_028', 'default', 'A small site or API slice can land in a few weeks. A directory, booking, or coaching platform is usually one to three months for a first honest version. Timing on the contact form (soon / 1–3 months / later) is how I plan around Centurion work.', NOW(), NOW()),
  ('ans_029_1', 'faq_029', 'default', 'I work at Centurion PLC and take selected freelance work around that. Start dates depend on scope. If you need something immediately, say so on the contact form and I’ll tell you the first open window.', NOW(), NOW()),
  ('ans_030_1', 'faq_030', 'default', 'Larger products are phased: a first live slice, then the rest. Expect months, not a weekend. I’ll still give you something clickable early so you can judge the work before the whole map is drawn.', NOW(), NOW()),
  ('ans_031_1', 'faq_031', 'default', 'Yes — selected work, not every inbound. Full-time is Centurion PLC; freelance is scoped around that. The inbox is open: raza.aursoft@gmail.com or the contact form.', NOW(), NOW()),
  ('ans_032_1', 'faq_032', 'default', 'I am based in the Maldives and have shipped product work from Fujairah, UAE. Remote is normal. I overlap Gulf and South-Asia hours easily; Europe is fine with async updates.', NOW(), NOW()),
  ('ans_033_1', 'faq_033', 'default', 'Email for briefs and files. WhatsApp for short status. I write clearly and don’t hide behind process. If your team lives in Slack, I can join for the duration of the work.', NOW(), NOW()),
  ('ans_034_1', 'faq_034', 'default', 'Email raza.aursoft@gmail.com, phone +971 54 271 4360, or WhatsApp on that number. The contact form on /contact is the cleanest way to include budget and timing.', NOW(), NOW()),
  ('ans_035_1', 'faq_035', 'default', 'Launch is not the end. I fix defects from the build, then we can move to a retainer for updates and performance. At Aursoft, post-launch support held high client satisfaction. Say if you want ongoing care on the contact form.', NOW(), NOW()),
  ('ans_036_1', 'faq_036', 'default', 'I can deploy to AWS, Vercel, or the PHP host you already pay for, and keep an eye on uptime when we agree a retainer. I don’t lock you into a host I own — you should keep the accounts.', NOW(), NOW()),
  ('ans_037_1', 'faq_037', 'default', 'Production web work since Aursoft in 2018 (8+ years), and web development with PHP since 2015. BSCS from AWKUM, 2015–2019. Employers: Aursoft, Ferisoft, Fujtown, now Centurion PLC.', NOW(), NOW()),
  ('ans_038_1', 'faq_038', 'default', 'Aursoft (2018–2021, Islamabad), Ferisoft (2021–2022, remote Türkiye), Fujtown (2023–May 2026, Fujairah), Centurion PLC (July 2026–present). The career walk on /career is the same timeline, in order.', NOW(), NOW()),
  ('ans_039_1', 'faq_039', 'default', 'Yes. Leave your email and phone here if this chat doesn’t cover it, or use /contact. I’ll reply with a time that works around the Centurion day.', NOW(), NOW()),
  ('ans_040_1', 'faq_040', 'default', 'Yes. fujtown.com is Laravel with Vue.js for the directory UI: registration, listings, search, and roles. I reach for React or Next.js on new fronts, and Vue when the product is already there.', NOW(), NOW()),
  ('ans_041_1', 'faq_041', 'default', 'Yes. Tailwind on Fujtown-era and current React/Next work. I also ship Bootstrap when that is the existing design system, as on FOIZ and SisTouristVilla.', NOW(), NOW()),
  ('ans_042_1', 'faq_042', 'default', 'PHP since 2015. Laravel and CodeIgniter in production at Aursoft and Fujtown. Inventory/POS at inventory.aursoft.com is CodeIgniter 3 with Sencha. I still take PHP products that have to stay live, not only greenfield Next.js.', NOW(), NOW()),
  ('ans_043_1', 'faq_043', 'default', 'Yes. Firebase showed up in backend work at Ferisoft alongside Node and Laravel. I use it when auth, hosting, or realtime fits; SQL stays the default for booking and inventory.', NOW(), NOW()),
  ('ans_044_1', 'faq_044', 'default', 'Yes. Directories and coaching platforms need businesses vs admins, students vs operators. fujtown.com has authentication and role-based access. I wire the roles to the real jobs, not a generic user table.', NOW(), NOW()),
  ('ans_045_1', 'faq_045', 'default', 'Yes. Listing management, booking/ops screens, inventory, invoices, and reporting. The driving-school platform includes scheduling and pass-rate reporting. Admin tools are usually Laravel or a React/Next front on the same APIs.', NOW(), NOW()),
  ('ans_046_1', 'faq_046', 'default', 'Yes. Performance and SEO are part of how I ship, not an add-on slide. Public sites at Fujtown and Centurion work need to stay fast. Send the URL and whether the pain is crawl, LCP, or a heavy admin.', NOW(), NOW()),
  ('ans_047_1', 'faq_047', 'default', 'Yes. Public products are built to work on a phone first. Directories, booking, and coaching UIs are useless if they only look right on a laptop. I check the flows that matter on a small screen, not only a desktop mock.', NOW(), NOW()),
  ('ans_048_1', 'faq_048', 'default', 'Yes. Fujairah Fine Arts Academy is a bilingual English/Arabic layout. RTL, copy in two languages, and a CMS the staff can actually edit are the usual constraints. Tell me which language is source of truth.', NOW(), NOW()),
  ('ans_049_1', 'faq_049', 'default', 'FOIZ is the Fujairah Oil Industry Zone marketplace. I worked on API and backend queries in Laravel and PostgreSQL, plus feature work and UI improvements. Live at foiz.gov.ae.', NOW(), NOW()),
  ('ans_050_1', 'faq_050', 'default', 'SisTouristVilla is a hotel booking site I led: planning, design, payment gateway, and APIs so guests can book rooms online. PHP, JavaScript, MySQL, Bootstrap 5. Live at sistouristvilla.com.', NOW(), NOW()),
  ('ans_051_1', 'faq_051', 'default', 'fujtown.com is a full-stack business directory: registration, listing management, search, auth, and roles for businesses and admins. Laravel and Vue.js. I also did product-based full-stack work at Fujtown LLC from 2023 to May 2026.', NOW(), NOW()),
  ('ans_052_1', 'faq_052', 'default', 'Yes. inventory.aursoft.com is inventory and POS in CodeIgniter 3 and Ext-Sencha: live stock, low-stock alerts, invoices, customers, and sales reporting. At Fujtown a custom inventory build improved stock-tracking accuracy by about 35%.', NOW(), NOW()),
  ('ans_053_1', 'faq_053', 'default', 'Yes. The coaching product uses Next.js and Laravel: auth, payments, subscriptions, courses and challenges, onboarding questionnaires, calorie calculators, and progress tracking. That is the closest public example of a membership product.', NOW(), NOW()),
  ('ans_054_1', 'faq_054', 'default', 'You keep the product accounts: domain, host, GitHub, payments. I deliver the repo and a handover. I don’t hold the keys after the work unless you ask me to retain on a named account.', NOW(), NOW()),
  ('ans_055_1', 'faq_055', 'default', 'Yes. Env list, how to deploy, and the few commands that matter. At Fujtown, documentation cut project delays about 20%. I won’t write a novel nobody reads — I’ll write what the next engineer needs.', NOW(), NOW()),
  ('ans_056_1', 'faq_056', 'default', 'If it changes the outcome, we re-quote that slice. Small copy and layout fixes inside the agreed screens stay in the work. I would rather pause and price a new module than silently grow a fixed bid.', NOW(), NOW()),
  ('ans_057_1', 'faq_057', 'default', 'I can implement a Figma file tightly, and I have worked with design on interfaces that lifted engagement. I am not a brand studio. If you have no designer, we keep the UI simple and consistent rather than inventing a visual identity from nothing.', NOW(), NOW()),
  ('ans_058_1', 'faq_058', 'default', 'Goal, URL or references, timing, and a budget mark (the contact form covers that). Then repo or host access, payment credentials if we touch checkout, and who signs off. A one-page brief beats a 40-page spec that nobody maintains.', NOW(), NOW()),
  ('ans_059_1', 'faq_059', 'default', 'Yes. GitHub is how the work moves. At Aursoft, automated deploys shortened release cycles about 40%. Staging, then production. You can see the history; I don’t ship from a laptop unzip.', NOW(), NOW()),
  ('ans_060_1', 'faq_060', 'default', 'Auth that is actually checked, parameterized queries, HTTPS, and least privilege on the server. At Fujtown, cPanel and server hardening cut downtime about 15%. I don’t run a pentest theatre on a brochure site; I do lock the doors that production actually uses.', NOW(), NOW()),
  ('ans_061_1', 'faq_061', 'default', 'Yes, for scoped Laravel/React/Next/PHP work, including existing codebases. I stay in your tools and your client’s name if that is the deal. NDA first if the end client is confidential.', NOW(), NOW()),
  ('ans_062_1', 'faq_062', 'default', 'Yes. Professional work has been in English across Pakistan, Türkiye (remote), the UAE, and the Maldives. I write status in plain sentences. Arabic UI copy I implement; I don’t pretend to be a native Arabic copywriter.', NOW(), NOW()),
  ('ans_063_1', 'faq_063', 'default', 'Quoted in USD. Typical shape is a start payment, then the rest on agreed slices you can click. Exact split is in the quote, not a surprise at the end. The contact form’s USD 100–5,000 slider is the conversation starter, not a hidden hourly trap.', NOW(), NOW()),
  ('ans_064_1', 'faq_064', 'default', 'Not as a WordPress specialist. If you need custom PHP, Laravel, React, or Next.js, that is the work. A simple WP brochure is usually faster with someone who lives in that stack. I can still rescue a PHP site that has grown past a theme.', NOW(), NOW()),
  ('ans_065_1', 'faq_065', 'default', 'No native apps. I build web products that work well on a phone, including booking and membership flows. If you need App Store binaries, pair me with a mobile engineer or keep the product on the web.', NOW(), NOW()),
  ('ans_066_1', 'faq_066', 'default', 'Centurion is the weekday job. Freelance sits around that — evenings and planned windows, not 24/7 chat. Europe and Gulf overlap is fine with async notes. Rush weekends get called out in the quote.', NOW(), NOW()),
  ('ans_067_1', 'faq_067', 'default', 'I am employed at Centurion PLC (July 2026–present). I take selected freelance and product work. A full-time move is a different conversation — use the contact form and say so clearly.', NOW(), NOW()),
  ('ans_068_1', 'faq_068', 'default', 'Full-stack engineer since July 2026: production web platforms after the Fujtown handover. React, Next.js, Laravel, and PHP — UI, APIs, and deploys, with performance and SEO on live systems.', NOW(), NOW()),
  ('ans_069_1', 'faq_069', 'default', 'Full-stack product work, March 2023–May 2026, Fujairah: React, Next.js, Tailwind, Laravel, CodeIgniter, PostgreSQL/MySQL. Directory and booking products, inventory accuracy, less downtime, fewer production bugs. fujtown.com is the public directory.', NOW(), NOW()),
  ('ans_070_1', 'faq_070', 'default', 'BSCS, AWKUM University, 2015–2019, and a Diploma in Information Technology. The useful part is production work since 2018, not the paper.', NOW(), NOW()),
  ('ans_071_1', 'faq_071', 'default', 'GitHub github.com/razaali333, LinkedIn linkedin.com/in/raza-ali-626a12190, résumé at razaali.vercel.app/resume.pdf. Live products are on /work — that is stronger than a repo dump.', NOW(), NOW()),
  ('ans_072_1', 'faq_072', 'default', 'Defects from the build get fixed. New ideas are new work or a retainer. If you want me on-call for uptime, say so up front so it is in the quote, not assumed.', NOW(), NOW()),
  ('ans_073_1', 'faq_073', 'default', 'You talk to the person who ships. 8+ years of live Laravel/React/PHP products — directories, booking, APIs, inventory — not a bench of juniors. Agencies are right for brand theatre; I am right when the site has to stay up.', NOW(), NOW());
